apiVersion: v1
kind: Service
metadata:
  labels:
    name: data-broker-redis
  name: data-broker-redis
  namespace: dojot
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: data-broker-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: data-broker-redis
  name: data-broker-redis
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: data-broker-redis
    spec:
      containers:
      - image: redis
        name: data-broker-redis
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: data-broker
  name: data-broker
  namespace: dojot
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: data-broker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: data-broker
  name: data-broker
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: data-broker
    spec:
      containers:
      - image: dojot/data-broker:latest
        name: data-broker
      restartPolicy: Always
