apiVersion: v1
kind: Service
metadata:
  labels:
    name: iotagent-mqtt
  name: iotagent-mqtt
  namespace: dojot
spec:
  ports:
  - name: mqtt-insecure
    port: 1883
    targetPort: 1883
  - name: mqtt-secure
    port: 8883
    targetPort: 8883
  selector:
    name: iotagent-mqtt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: iotagent-mqtt
  name: iotagent-mqtt
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iotagent-mqtt
        app: external-mqtt
    spec:
      containers:
      - image: dojot/iotagent-mosca:latest
        name: iotagent-mqtt
        env:
        - name: BACKEND_HOST
          value: iotagent-mqtt-redis
        - name: KAFKA_ADDRESS
          value: kafka-server:9092
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: iotagent-mqtt-redis
  name: iotagent-mqtt-redis
  namespace: dojot
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: iotagent-mqtt-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: iotagent-mqtt-redis
  name: iotagent-mqtt-redis
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iotagent-mqtt-redis
    spec:
      containers:
      - image: redis
        name: iotagent-mqtt-redis
      restartPolicy: Always
