apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-server
  name: kafka-server
  namespace: dojot
spec:
  ports:
  - name: "kafka-server"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka-server
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    name: kafka-server
  name: kafka-server
  namespace: dojot
spec:
  serviceName: kafka-server
  updateStrategy:
    type: RollingUpdate
  securityContext:
    privileged: true
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka-server
    spec:
      containers:
      - image: ericbaum/kafka:0.10.2.1
        name: kafka-server
        ports:
        - containerPort: 9092
        env:
        - name: ZOOKEEPER_IP
          value: "zk-client"
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        volumeMounts:
         - name: kafka-volume
           mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: kafka-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dojot
      resources:
        requests:
          storage: 1Gi
