kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb
  namespace: dojot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-role
  namespace: dojot
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-role-binding
  namespace: dojot
subjects:
- kind: ServiceAccount
  name: mongodb
  namespace: dojot
roleRef:
  kind: Role
  name: mongo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongodb
  namespace: dojot
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongodb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dojot
spec:
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: mongodb
          image: mongo:3.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "name=mongodb"
            - name: KUBE_NAMESPACE
              value: dojot
      serviceAccountName: mongodb
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dojot
      resources:
        requests:
          storage: 1Gi


