apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-cluster
  name: postgres-cluster
  namespace: dojot
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
