apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: dojot
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    name: rabbitmq
---
# TODO: Add persistence
# TODO: Add clusterization
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
      restartPolicy: Always
