apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-kong
  name: external-kong
  namespace: dojot
spec:
  type: LoadBalancer
  ports:
  - name: "ext-http"
    port: 80
    targetPort: 8000
  - name: "ext-https"
    port: 443
    targetPort: 8443
  selector:
    app: external-kong
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-mqtt
  name: external-mqtt
  namespace: dojot
spec:
  type: LoadBalancer
  ports:
  - name: "ext-mqtt-insecure"
    port: 1883
    targetPort: 1883
  - name: "ext-mqtt-secure"
    port: 8883
    targetPort: 8883
  selector:
    app: external-mqtt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-coap
  name: external-coap
  namespace: dojot
spec:
  type: LoadBalancer
  ports:
  - name: "ext-coap"
    port: 5684
    protocol: UDP
    targetPort: 5684
  selector:
    app: external-coap
