kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: postgres-role
  namespace: dojot
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "list", "patch"]