kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: postgres-role-1
  namespace: dojot
subjects:
- kind: ServiceAccount
  name: postgres
  namespace: dojot
roleRef:
  kind: Role
  name: postgres-role
  apiGroup: rbac.authorization.k8s.io